name: flapp
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - alembic=1.3.1=py_0
  - blas=1.0=mkl
  - blast=2.9.0=h58d6d27_1
  - boost=1.68.0=py37h9888f84_1001
  - boost-cpp=1.68.0=h6f8c590_1000
  - bzip2=1.0.8=h0b31af3_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37hc8dfbb8_1
  - click=7.0=py37_0
  - flask=1.1.1=py_0
  - flask-migrate=2.4.0=py37_0
  - flask-redis=0.4.0=py_0
  - flask-sqlalchemy=2.4.0=py_0
  - flask-wtf=0.14.2=py37_1
  - gettext=0.19.8.1=h46ab8bc_1002
  - gmp=6.1.2=h0a44026_1000
  - gnutls=3.6.5=h53004b3_1002
  - icu=58.2=h0a44026_1000
  - intel-openmp=2019.4=233
  - itsdangerous=1.1.0=py37_0
  - jinja2=2.10.3=py_0
  - krb5=1.16.1=hddcf347_7
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=h0b31af3_1006
  - libpq=11.2=h051b688_0
  - mako=1.1.0=py_0
  - markupsafe=1.1.1=py37h1de35cc_0
  - mkl=2019.4=233
  - mkl-service=2.3.0=py37hfbe908c_0
  - mkl_fft=1.0.15=py37h5e564d8_0
  - mkl_random=1.1.0=py37ha771720_0
  - ncurses=6.1=h0a44026_1
  - nettle=3.4.1=h3efe00b_1002
  - numpy-base=1.18.1=py37h6575580_1
  - openssl=1.1.1=h1de35cc_0
  - pandas=1.0.0=py37h6c726b0_0
  - pcre=8.43=h0a44026_0
  - perl=5.26.2=haec8ef5_1006
  - perl-archive-tar=2.32=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526h6de7cb9_0
  - perl-compress-raw-zlib=2.087=pl526h770b8ee_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-io-compress=2.087=pl526h6de7cb9_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h04f5b5a_3
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-pathtools=3.75=pl526h1de35cc_1
  - perl-scalar-list-utils=1.52=pl526h01d97ff_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-xsloader=0.24=pl526_0
  - pip=19.3.1=py37_0
  - psycopg2=2.8.3=py37ha12b0ac_0
  - python=3.7.5=h359304d_0
  - python-dateutil=2.8.1=py_0
  - python-editor=1.0.4=py_0
  - python_abi=3.7=1_cp37m
  - pytz=2019.3=py_0
  - readline=7.0=h1de35cc_5
  - redis-py=3.3.11=py_0
  - setuptools=41.6.0=py37_0
  - six=1.13.0=py37_0
  - sqlalchemy=1.3.10=py37h1de35cc_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - wtforms=2.2.1=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - alabaster==0.7.12
    - attrs==19.3.0
    - babel==2.8.0
    - biopython==1.76
    - chardet==3.0.4
    - codecov==2.0.15
    - coverage==5.0.3
    - dicttoxml==1.7.4
    - docutils==0.16
    - enasearch==0.2.0
    - entrypoints==0.3
    - flake8==3.7.9
    - flask-session==0.3.1
    - idna==2.8
    - imagesize==1.2.0
    - importlib-metadata==1.4.0
    - inflect==4.1.0
    - mccabe==0.6.1
    - more-itertools==8.1.0
    - numpy==1.18.1
    - packaging==20.1
    - pluggy==0.13.1
    - py==1.8.1
    - pycodestyle==2.5.0
    - pyflakes==2.1.1
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pytest==5.3.4
    - pytest-cov==2.8.1
    - requests==2.22.0
    - snowballstemmer==2.0.0
    - sphinx==2.3.1
    - sphinx-rtd-theme==0.4.3
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlacodegen==2.1.0
    - tabulate==0.8.6
    - urllib3==1.25.8
    - wcwidth==0.1.8
    - xmltodict==0.12.0
    - zipp==2.1.0
prefix: /opt/miniconda3/envs/flapp

