name: flapp
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - autoflake=1.3=py_0
  - blast=2.10.1=pl526he19e7b1_1
  - bzip2=1.0.8=h516909a_2
  - c-ares=1.16.1=h516909a_0
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py38h32f6830_0
  - curl=7.71.1=he644dc0_4
  - entrez-direct=13.3=pl526h375a9b1_0
  - expat=2.2.9=he1b5a44_2
  - isort=5.4.2=py38h32f6830_0
  - krb5=1.17.1=hfafb76e_2
  - ld_impl_linux-64=2.34=hc38a660_9
  - libcurl=7.71.1=hcdd3856_4
  - libcxx=10.0.1=hc9558a2_0
  - libcxxabi=10.0.1=0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.3.0=h24d8f2e_15
  - libgomp=9.3.0=h24d8f2e_15
  - libnghttp2=1.41.0=hab1572f_1
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.3.0=hdf63c60_15
  - ncurses=6.2=he1b5a44_1
  - openssl=1.1.1g=h516909a_1
  - pcre=8.44=he1b5a44_0
  - perl=5.26.2=h516909a_1006
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-base=2.23=pl526_1
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-constant=1.33=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-temp=0.2304=pl526_2
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tree=5.07=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-zlib=1.10=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-libwww-perl=6.39=pl526_0
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-mime-base64=3.15=pl526_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-parent=0.236=pl526_1
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-socket=2.027=pl526_1
  - perl-storable=3.15=pl526h14c3975_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-time-local=1.28=pl526_1
  - perl-try-tiny=0.30=pl526_1
  - perl-types-serialiser=1.0=pl526_2
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-simple=2.25=pl526_1
  - perl-xsloader=0.24=pl526_0
  - pip=20.2.2=py_0
  - pyflakes=2.2.0=pyh9f0ad1d_0
  - python=3.8.5=h4d41432_2_cpython
  - python_abi=3.8=1_cp38
  - readline=8.0=he28a2e2_2
  - setuptools=49.6.0=py38h32f6830_0
  - sqlite=3.32.3=h4cf870e_1
  - tk=8.6.10=hed695b0_0
  - wheel=0.35.1=pyh9f0ad1d_0
  - xz=5.2.5=h516909a_1
  - zlib=1.2.11=h516909a_1007
  - pip:
    - chardet==3.0.4
    - click==7.1.2
    - flask==1.1.2
    - flask-wtf==0.14.3
    - idna==2.10
    - itsdangerous==1.1.0
    - jinja2==2.11.2
    - markupsafe==1.1.1
    - numpy==1.19.1
    - pandas==1.1.0
    - python-dateutil==2.8.1
    - pytz==2020.1
    - requests==2.24.0
    - six==1.15.0
    - tabulate==0.8.7
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - wtforms==2.3.3
prefix: /home/ubuntu/miniconda3/envs/flapp

